package openperipheral;

import java.io.InputStreamReader;
import java.io.Reader;
import java.net.URL;
import java.net.URLConnection;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map.Entry;

import net.minecraft.src.ModLoader;
import net.minecraft.tileentity.TileEntity;
import net.minecraftforge.common.Configuration;
import net.minecraftforge.common.Property;
import openperipheral.converter.ConverterArray;
import openperipheral.converter.ConverterDouble;
import openperipheral.converter.ConverterForgeDirection;
import openperipheral.converter.ConverterILiquidTank;
import openperipheral.converter.ConverterItemStack;
import openperipheral.converter.appliedenergistics.ConverterIMEInventory;
import openperipheral.converter.buildcraft.ConverterPowerProvider;
import openperipheral.converter.forestry.ConverterEnumHumidity;
import openperipheral.converter.forestry.ConverterEnumTemperature;
import openperipheral.converter.forestry.ConverterFruitFamily;
import openperipheral.converter.thaumcraft.ConverterEnumTag;
import openperipheral.converter.thaumcraft.ConverterObjectTags;
import openperipheral.definition.DefinitionClass;
import openperipheral.definition.DefinitionMethod;
import openperipheral.definition.DefinitionMod;
import openperipheral.definition.ModList;
import openperipheral.postchange.PostChangeMarkUpdate;
import openperipheral.postchange.PostChangePortalGun;
import openperipheral.restriction.RestrictionChoice;
import openperipheral.restriction.RestrictionMaximum;
import openperipheral.restriction.RestrictionMinimum;
import argo.jdom.JdomParser;
import argo.jdom.JsonNode;
import argo.jdom.JsonRootNode;
import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.Mod.Instance;
import cpw.mods.fml.common.event.FMLInitializationEvent;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;
import cpw.mods.fml.common.registry.TickRegistry;
import cpw.mods.fml.relauncher.Side;
import dan200.computer.api.ComputerCraftAPI;


@Mod( modid = "OpenPeripheral", name = "OpenPeripheral", version = "0.1.0", dependencies = "after:BuildCraft|Core;after:AppliedEnergistics;after:Forestry;after:IC2;after:ThermalExpansion;after:Thaumcraft;after:MineFactoryReloaded;after:Railcraft")
public class OpenPeripheral
{

	public static ModList definitions = new ModList();
	public static HashMap<Class, DefinitionClass> classList = new HashMap<Class, DefinitionClass>();
	
	@Instance( value = "OpenPeripheral" )
	public static OpenPeripheral instance;

	@Mod.PreInit
	public void preInit( FMLPreInitializationEvent evt )
	{
		Configuration configFile = new Configuration(evt.getSuggestedConfigurationFile());
		
		Property prop = configFile.get("general", "enableAnalytics", true);
		prop.comment = "Do you want analytics enabled?";
		
		prop = configFile.get("general", "currentVersion", "0.2.0");
		prop.comment = "Do not edit this file. OpenPeripheral adds no blocks or items! this value should not be changed";
		
		configFile.save();
	}

	@Mod.Init
	public void init( FMLInitializationEvent evt )
	{
		RestrictionFactory.registerRestrictionHandler("min", new IRestrictionHandler() {
			@Override
			public IRestriction createFromJson(JsonNode json) {
				return new RestrictionMinimum(json);
			}
		});

		RestrictionFactory.registerRestrictionHandler("max", new IRestrictionHandler() {
			@Override
			public IRestriction createFromJson(JsonNode json) {
				return new RestrictionMaximum(json);
			}
		});
		
		RestrictionFactory.registerRestrictionHandler("choice", new IRestrictionHandler() {
			@Override
			public IRestriction createFromJson(JsonNode json) {
				return new RestrictionChoice(json);
			}
		});

		PostChangeRegistry.registerChangeHandler(new PostChangeMarkUpdate());

		TypeConversionRegistry.registryTypeConverter(new ConverterArray());
		TypeConversionRegistry.registryTypeConverter(new ConverterDouble());
		TypeConversionRegistry.registryTypeConverter(new ConverterItemStack());
		TypeConversionRegistry.registryTypeConverter(new ConverterILiquidTank());
		TypeConversionRegistry.registryTypeConverter(new ConverterForgeDirection());
		
		if (ModLoader.isModLoaded(Mods.APPLIED_ENERGISTICS)){
			TypeConversionRegistry.registryTypeConverter(new ConverterIMEInventory());
		}
		if (ModLoader.isModLoaded(Mods.FORESTRY)){
			TypeConversionRegistry.registryTypeConverter(new ConverterEnumHumidity());
			TypeConversionRegistry.registryTypeConverter(new ConverterEnumTemperature());
			TypeConversionRegistry.registryTypeConverter(new ConverterFruitFamily());
		}
		if (ModLoader.isModLoaded(Mods.BUILDCRAFT)) {
			TypeConversionRegistry.registryTypeConverter(new ConverterPowerProvider());
		}
		if (ModLoader.isModLoaded(Mods.THAUMCRAFT)) {
			TypeConversionRegistry.registryTypeConverter(new ConverterObjectTags());
			TypeConversionRegistry.registryTypeConverter(new ConverterEnumTag());
		}
		if (ModLoader.isModLoaded(Mods.PORTAL_GUN)) {
			PostChangeRegistry.registerChangeHandler(new PostChangePortalGun());
		}
		
		JsonRootNode rootNode = loadJSON();
		
		if (rootNode != null) {
		    for (JsonNode modNode : rootNode.getElements()) {
		    	DefinitionMod definition = new DefinitionMod(modNode);
		    	classList.putAll(definition.getValidClasses());
				/*		    	
				if (definition.getModId().equals("") || ModLoader.isModLoaded(definition.getModId())) {
						    		
				}
				*/
		    }
		}
		

		TickRegistry.registerTickHandler(new TickHandler(), Side.SERVER);
		ComputerCraftAPI.registerExternalPeripheral(TileEntity.class, new PeripheralHandler());
		
	}
	
	public static ArrayList<DefinitionMethod> getMethodsForClass(Class klass) {
		
		ArrayList<DefinitionMethod> methods = new ArrayList<DefinitionMethod>();
		for (Entry<Class, DefinitionClass> entry : classList.entrySet()) {
			if (entry.getKey().isAssignableFrom(klass)) {
				methods.addAll(entry.getValue().getMethods());
			}
		}
		
		return methods;
	}

	private JsonRootNode loadJSON() {
		URL url;
		try {
			//url = new URL("https://raw.github.com/mikeemoo/OpenPeripheral/master/methods.json");
			url = new URL("http://localhost/methods_new.json");
			URLConnection con = url.openConnection();
			Reader r = new InputStreamReader(con.getInputStream(), "UTF-8");
		    JdomParser parser = new JdomParser();
		    JsonRootNode root = parser.parse(r);
		    r.close();
		    return root;
		} catch (Exception e) {
			e.printStackTrace();
		}
		return null;
	}

}