package openperipheral.api;

/**
 * Various constants used in API methods.
 */
public class Constants {
	public static final String ARCH_COMPUTER_CRAFT = "ComputerCraft";
	public static final String ARCH_OPEN_COMPUTERS = "OpenComputers";

	/**
	 * IMC command for appending class to tile entity blacklist.
	 * OpenPeripheral will not provide peripheral implementation for blacklisted classes.
	 * Parameter: full class
	 */
	public static final String IMC_IGNORE = "ignoreTileEntity";

	/**
	 * IMC command for setting type of peripherals created from requested class.
	 * This command can be used to replace autogenerated name.
	 * Parameter: full class, whitespace, new peripheral type
	 */
	public static final String IMC_NAME_CLASS = "registerClassType";
}
